system-ghc: false

# ghc 8.4.4
# resolver: lts-12.16

# ghc 8.6.1
#resolver: nightly-2018-10-03

# ghc 8.10.4
resolver: lts-17.15

# Local packages, usually specified by relative directory name
packages:
- '.'
# - ../flat

flags:
   serialise:
     newtime15: true

# ghc 8.4.4
# extra-deps:
# - flat-0.3.4
# - persist-0.1
# - packman-0.5.0
# # - binary-0.8.5.1
# - cereal-0.5.7.0
# - store-0.5.0.1
# - serialise-0.2.1.0
# - datasets-0.2.1

extra-deps:
- flat-0.4.4
- persist-0.1.1.5
# No loner maintained. Errors in cbits. This dependency should be removed for now.
# - packman-0.5.0
- binary-0.8.8.0
- cereal-0.5.8.1
- store-0.7.11
- serialise-0.2.3.0

# datasets
# TODO The data sets are acquired at run-time. Make sure that their metadata is also modifiable at run-time.
#      For this matter, simply provide a Dhall configuration.
# TODO Depend on my github or gitlab branch.
- third-party/dh-core/datasets

- winery-1.3.2
- barbies-th-0.1.8@sha256:2855c0f80c683ad30295370e5d9e786d909355695054ae4126ae61ea5c7779c4,1085
- fast-builder-0.1.2.1@sha256:6e3148d9ac21e5ec900fa59d1d65322e6b4c0491f19b53bdbe093186a519eb9f,2791
- streaming-cassava-0.2.0.0@sha256:aea99400ef6e7fa064bb275601503544608b8e3fbee6f6c661b019033dc40d11,1812